### ISSUE TITLE
i only generate .d.ts files when i switch the option "declarationMap" ;

### ISSUE THREAD

**Issue by tonyload** [Floffah/esbuild-plugin-d.ts#10]
i use esbuild-plugin-d.ts only generate generate .d.ts files when i change the ts.config.json's value "declarationMap" from TRUE to FALSE or from FALSE from TRUE:
i think it would be e issue.

if i dont change  ts.config.json file, only run npm run  build, the .d.ts files cant be created the secrec time!

**Comment by Floffah** [comment]
This issue is likely fixed in 1.2.0
