### ISSUE TITLE
tsup https://github.com/Floffah/esbuild-plugin-d.ts/pull/11

### ISSUE THREAD

**Issue by seanwessmith** [Floffah/esbuild-plugin-d.ts#12]
fixed types issue with tsup by bumping the package version and all other packages in the repo.

 unmet peer typescript@^4.1.0: found 5.0.4

https://github.com/Floffah/esbuild-plugin-d.ts/pull/11

**Comment by HarikalarKutusu** [comment]
Thank you for this! When upgrading my monorepo to ts 5.x today, I had to remove this plugin. And of course, my libraries are not working. Because this is not merged yet, I had to fork it, upfdate it and use `pnpm add` from my github.

It will be best if it is merged of course.

**Comment by seanwessmith** [comment]
🎉
