### ISSUE TITLE
Use with ES6

### ISSUE THREAD

**Issue by Mqxx** [Floffah/esbuild-plugin-d.ts#15]
Hey, how can I use this plugin using ES6 import syntax instead of common js require?

**Comment by Floffah** [comment]
The plugin is published with an es6 bundle that your runtime should pick up automatically. You can import it either as a default import or using the exported function, e.g.
```ts
import dtsPlugin from "esbuild-plugin-d.ts";
// or
import { dtsPlugin } from "esbuild-plugin-d.ts";
```

**Comment by Mqxx** [comment]
Okay, thanks for the information! Maybe you could update the readme so that others can see this 👍
