### ISSUE TITLE
tsconfig.json required when using experimentalBundling

### ISSUE THREAD

**Issue by Hexagon** [Floffah/esbuild-plugin-d.ts#17]
Experimenting with using this library to build and bundle Croner (https://github.com/Hexagon/croner/tree/dev ) with only Deno + Esbuild.

I figured out the hard way - to make experimentalBundling work, i have to add a valid tsconfig.json mirroring the settings i pass to the plugin. It seems like the ts bundler ignores passed settings, and uses tsconfig.json instead.

Would like to avoid a separate tsconfig.json to keep the repo as clean as possible :ninja:

**Comment by Floffah** [comment]
Hm, it seems to be a limitation with the [dts bundling library](https://npm.im/dts-bundle-generator) I'm using - I will push a new canary build that can work around this. The plugin will need to save a temporary tsconfig file based on your passed config that it will delete post build.

**Comment by Floffah** [comment]
Ignore the comment from the bot - I have pushed a build ([1.3.1-canary.1](https://github.com/Floffah/esbuild-plugin-d.ts/releases/tag/v1.3.1-canary.1)) that may fix this. Please try it and give feedback

**Comment by Hexagon** [comment]
Will try it out asap :+1: :rocket:

**Comment by Hexagon** [comment]
Three issues popped up trying this, some could be related to me using the library through Deno. But it works like a charm if i create the tsconfig manually and omit tsconfig: { ... }

Input `plugins:`
```ts
[dtsPlugin({ 
  experimentalBundling: true,
  tsconfig: {
    declarations: true,
    compilerOptions: {
      emitDeclarationOnly: true,
      allowImportingTsExtensions: true,
      target: "es2015"
    }
  }
})]
```


#### 1. The tsconfig `target:` is incorrectly generated as `2` instead of `"es2015"`

```bash
abc@bc928c21822e:~/workspace/croner$ deno task build
Task build deno task build:prep && deno task build:clean && deno task build:esbuild && deno task test && deno task build:npm
Task build:prep deno cache --allow-scripts=npm:esbuild build/build.ts
Task build:clean deno run --allow-read --allow-write --allow-env build/build.ts -- clean
Task build:esbuild deno run --allow-read --allow-write --allow-env --allow-run build/build.ts -- build
error TS5024: Compiler option 'target' requires a value of type string.
Build failed: Error: Build failed with 1 error:
error: Error while processing tsconfig compiler options
    at failureErrorWithLog (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:1476:15)
    at file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:945:25
    at file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:1354:9
    at runOnEndCallbacks (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:1355:9)
    at buildResponseToResult (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:943:7)
    at file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:970:16
    at responseCallbacks.<computed> (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:622:9)
    at handleIncomingPacket (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:677:12)
    at Readable.readFromStdout (file:///config/.cache/deno/npm/registry.npmjs.org/esbuild/0.24.0/lib/main.js:600:7)
    at Readable.emit (ext:deno_node/_stream.mjs:1851:9) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

The temporary file:

```json
{"declarations":true,"compilerOptions":{"emitDeclarationOnly":true,"allowImportingTsExtensions":true,"target":2,"declaration":true,"declarationDir":"/config/workspace/croner/dist/dts-prebundle","listEmittedFiles":true},"include":["/config/workspace/croner/src/croner.ts"]}
```


#### 2. The temporary file is left in the repo after a failed build

#### 3. There seem to be some sort of typing problem with compilerOptions: {}

compilerOptions itself is ok, but none of the properties like target, emitDeclarationOnly etc. is

```bash
abc@bc928c21822e:~/workspace/croner$ deno check build/build.ts
Check file:///config/workspace/croner/build/build.ts
error: TS2353 [ERROR]: Object literal may only specify known properties, and 'emitDeclarationOnly' does not exist in type '{ alwaysStrict?: boolean | undefined; baseUrl?: string | undefined; experimentalDecorators?: boolean | undefined; importsNotUsedAsValues?: "remove" | "preserve" | "error" | undefined; ... 9 more ...; verbatimModuleSyntax?: boolean | undefined; }'.
            emitDeclarationOnly: true,
            ~~~~~~~~~~~~~~~~~~~
    at file:///config/workspace/croner/build/build.ts:47:13
````

**Comment by Floffah** [comment]
Thank you for the feedback, I will spend some more time debugging this and get a fix through tomomorrow

**Comment by Floffah** [comment]
this should now be fixed in [v1.3.1-canary.3](https://github.com/Floffah/esbuild-plugin-d.ts/releases/tag/v1.3.1-canary.3) - i also added a test to account for this use case which is passing

**Comment by Hexagon** [comment]
Works great now, thanks 👍

**Comment by Floffah** [comment]
> Works great now, thanks 👍

Perfect! Thank you for submitting this issue
