### ISSUE TITLE
Doesn't produce any output.

### ISSUE THREAD

**Issue by VentGrey** [Floffah/esbuild-plugin-d.ts#18]
The simplest configuration doesn't produce any output when used as is.

Entrypoint is set at `lib/index.ts`,  `dtsPlugin()` is being called "as is". There's no way to debug this fuckery around to see why is it not emitting anything.

**Comment by Floffah** [comment]
Lets try and stay positive about this, no need to be angry.

Would you be able to share a reproducable example of this? All of my tests pass fine. I will do some debugging of my own in the meantime to see if I can find the issue.

In reference to your debugging comment - I have wanted to overhaul the logging and commenting for a while. I will add a debug log level throughout the plugin when I get some time outside of uni.

**Comment by Floffah** [comment]
Closing as there is no more info, please reopen when you create a reproducable example
