### ISSUE TITLE
declarationDir or outDir does not work

### ISSUE THREAD

**Issue by TomokiMiyauci** [Floffah/esbuild-plugin-d.ts#2]
Hi!

This project is valuable because it can generate a declaration file as a plugin for `esbuild`.
Is it intentional that can't control the output destination of the type declaration file?

Minimum configuration to reproduce:
version:
```bash
node -v
v16.1.0
esbuild: 0.12.5
esbuild-plugin-d.ts: 1.0.2
typescript: 4.3.2
```

File structure
```bash
.
├── node_modules
├── build.js
├── mod.ts
├── package.json
├── tsconfig.json
└── yarn.lock
```

tsconfig.json
```json
{
    "compilerOptions": {
        "declaration": true,
        "declarationDir": "./dist",
    }
}
```

build.js
```js
import esbuild from "esbuild";
import { dtsPlugin } from "esbuild-plugin-d.ts";
esbuild
  .build({
    entryPoints: ["mod.ts"],
    bundle: true,
    outdir: "dist",
    plugins: [dtsPlugin()],
  })
  .catch(() => process.exit(1));
```

Now when I build it I get the following output.

```bash
node build.js
```

```bash
.
├── build.js
├── dist
│   └── mod.js
├── mod.d.ts
├── mod.ts
├── package.json
├── tsconfig.json
└── yarn.lock
```

The same result when `outDir` of `tsconfig` is set.
Is there a way to output the type declaration file under `dist`?

**Comment by Floffah** [comment]
In your tsconfig, try setting `outDir` to `./dist` and let me know if that fixes it. If it doesn't, ill try and reproduce this and fix it.
In the mean time, I will edit the plugin to set `outDir` in the typescript config to your esbuild `outdir` which should clear up some confusion.

**Comment by Floffah** [comment]
Found the issue,
Although the plugin was looking for the typescript configuration, it wasn't actually finding it or loading it.
It should now load your tsconfig file and even if it doesn't it will automatically fall back to the outdir set in the esbuild options.
