### ISSUE TITLE
Type for `compilerOptions` are incomplete

### ISSUE THREAD

**Issue by Hexagon** [Floffah/esbuild-plugin-d.ts#20]
compilerOptions itself is ok, but none of the properties like target, emitDeclarationOnly etc. is

```bash
abc@bc928c21822e:~/workspace/croner$ deno check build/build.ts
Check file:///config/workspace/croner/build/build.ts
error: TS2353 [ERROR]: Object literal may only specify known properties, and 'emitDeclarationOnly' does not exist in type '{ alwaysStrict?: boolean | undefined; baseUrl?: string | undefined; experimentalDecorators?: boolean | undefined; importsNotUsedAsValues?: "remove" | "preserve" | "error" | undefined; ... 9 more ...; verbatimModuleSyntax?: boolean | undefined; }'.
            emitDeclarationOnly: true,
            ~~~~~~~~~~~~~~~~~~~
    at file:///config/workspace/croner/build/build.ts:47:13
````

A little digging reveals that `TsconfigRaw` from esbuild is missing all settings related to declarations:

![image](https://github.com/user-attachments/assets/b9cb2c2f-8012-4119-b067-47e00d73ad94)

**Comment by Floffah** [comment]
Interesting, I was never able to find any other types (even exported by the ts package) that have the proper shape of a tsconfig file. I might toy with generating types from the provided jsonschema or just using `any`

**Comment by Hexagon** [comment]
I can have a look at a PR for this :+1:

**Comment by Floffah** [comment]
> I can have a look at a PR for this 👍

if you can think of a good solution feel free to have a bash
