### ISSUE TITLE
bug: Sometimes it doesn’t generate dts correctly, I’m not sure what happened, but obviously something went wrong

### ISSUE THREAD

**Issue by rxliuli** [Floffah/esbuild-plugin-d.ts#5]
![image](https://user-images.githubusercontent.com/24560368/134842286-8642b850-09a8-4718-b91f-6ed0a28a7250.png)

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext"],
    "outDir": "./dist",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "declarationMap": true
  },
  "include": ["src"],
  "typedocOptions": {
    "entryPoints": ["src/index.ts"],
    "out": "docs",
    "readme": "README.md",
    "gitRemote": "origin"
  }
}
```

Reproducible steps

1. git clone https://github.com/rxliuli/liuli-tools
2. cd liuli-tools
3. yarn
4. yarn setup
5. cd libs/i18next-util/dist

See error

**Comment by rxliuli** [comment]
In the end, I wrote similar logic to generate type definitions, but not as a plug-in of esbuild, but as an independent function, because it can generate type definitions only once when esbuild is run multiple times

**Comment by Floffah** [comment]
I will try and fix this asap, in the mean time I recommend a tool like [tsup](https://npm.im/tsup) which generates correct definition files (and is built on top of esbuild)

**Comment by rxliuli** [comment]
> I will try and fix this asap, in the mean time I recommend a tool like [tsup](https://npm.im/tsup) which generates correct definition files (and is built on top of esbuild)

Since we maintain the company's internal cli program, we cannot directly use a new one, and generally expect to be superimposed on the original cli

**Comment by Floffah** [comment]
I don't have a lot of time to look at this right now however I will open this again in case there is anyone out there who wants to fix this!
