### ISSUE TITLE
Plugin doesn't generate the tsconfig.tsbuildinfo file used for incremental builds

### ISSUE THREAD

**Issue by gablabelle** [Floffah/esbuild-plugin-d.ts#6]
When running `yarn tsc --build` I get an output `tsconfig.tsbuildinfo` file used the the Typescript incremental builds. Subsequent builds are much faster.

This file doesn't get generated when using `esbuild-plugin-d.ts`

Even if I specify the `tsBuildInfoFile` option, same thing.

```
{
  "extends": "../../tsconfig.settings.json",
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "tsconfig.tsbuildinfo",
    "outDir": "lib",
    "rootDir": "src"
  },
  "include": ["src/**/*"],
  "exclude": ["src/**/*.test.ts", "src/**/*.test.tsx"]
}
```

**Comment by gablabelle** [comment]
Also it seems that you should be using both createIncrementalProgram and createIncrementalCompilerHost in order to avoid the tsbuildinfo file to be ignore as [explained here](https://stackoverflow.com/questions/57554342/how-can-i-use-incremental-from-typescript-compiler-api)

According to the release notes 
> [For creating incremental builds, users can leverage the createIncrementalProgram and createIncrementalCompilerHost APIs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#apis-to-support---build-and---incremental).

You seem to be missing the createIncrementalCompilerHost usage at https://github.com/Floffah/esbuild-plugin-d.ts/blob/master/src/plugin.ts#L61

**Comment by Floffah** [comment]
Took a while to get round to it but I have switched to incremental programs and hosts and saw the build time for the test go down to 50ms. Let me know if this broke anything after installing [1.1.0](https://github.com/Floffah/esbuild-plugin-d.ts/releases/tag/1.1.0)
